version: '2'
services:
  invoice_project-app:
    image: invoice_project
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://invoice_project-postgresql:5432/invoice_project
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  invoice_project-postgresql:
    extends:
      file: postgresql.yml
      service: invoice_project-postgresql
